// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAptaqcEVukWCzYC9LwGYLy3qxXXaTwNjU',
    appId: '1:386693838269:web:b4d9b0238e347b96d5ced4',
    messagingSenderId: '386693838269',
    projectId: 'connextify-fe97a',
    authDomain: 'connextify-fe97a.firebaseapp.com',
    storageBucket: 'connextify-fe97a.appspot.com',
    measurementId: 'G-BJZZPMQ7RS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA8LhiZZCu5BXJBaaCLMUwgUvIFB5ZneoU',
    appId: '1:386693838269:android:57db9cefcf61d0a0d5ced4',
    messagingSenderId: '386693838269',
    projectId: 'connextify-fe97a',
    storageBucket: 'connextify-fe97a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCaKXTpl0HW_SaGu4y3Lkllh3YBsA69V3A',
    appId: '1:386693838269:ios:8d03aac9b1bd49e6d5ced4',
    messagingSenderId: '386693838269',
    projectId: 'connextify-fe97a',
    storageBucket: 'connextify-fe97a.appspot.com',
    iosBundleId: 'com.example.connectify',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCaKXTpl0HW_SaGu4y3Lkllh3YBsA69V3A',
    appId: '1:386693838269:ios:8d03aac9b1bd49e6d5ced4',
    messagingSenderId: '386693838269',
    projectId: 'connextify-fe97a',
    storageBucket: 'connextify-fe97a.appspot.com',
    iosBundleId: 'com.example.connectify',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAptaqcEVukWCzYC9LwGYLy3qxXXaTwNjU',
    appId: '1:386693838269:web:3d8fa677165a1e00d5ced4',
    messagingSenderId: '386693838269',
    projectId: 'connextify-fe97a',
    authDomain: 'connextify-fe97a.firebaseapp.com',
    storageBucket: 'connextify-fe97a.appspot.com',
    measurementId: 'G-5ECMJ482GD',
  );
}
